### ISSUE TITLE
where is positional encoding?

### ISSUE THREAD

**Issue by FreeRotate** [minqukanq/transformer-pytorch#2]

**Comment by minqukanq** [comment]
In this implementation, I use position embeddings as used in BERT instead of position encoding.
```python
self.word_embedding(x) + self.position_embedding(positions)
```

**Comment by FreeRotate** [comment]
> In this implementation, I use position embeddings as used in BERT instead of position encoding.
> 
> ```python
> self.word_embedding(x) + self.position_embedding(positions)
> ```

thank  you for your reply, but in original paper is sin&cos positional encoding instead of nn.Embedding

**Comment by minqukanq** [comment]
:)
